
require("NickyHariniaina.keymaps")
require("NickyHariniaina.lazy")
require("NickyHariniaina.options")

-- vim.api.nvim_create_user_command("FormatXml", function()
--   local buf = vim.api.nvim_get_current_buf()
--   local file = vim.api.nvim_buf_get_name(buf)
--
--   local result = os.execute("xmllint --format " .. vim.fn.shellescape(file) .. " -o " .. vim.fn.shellescape(file))
--
--   if result == true or result == 0 then
--     vim.cmd("edit!")
--     print("XML formatted with xmllint")
--   else
--     print("Failed to format XML")
--   end
-- end, { desc = "Format XML file with xmllint" })
--
-- -- Formats XML automaticall on save
-- vim.api.nvim_create_autocmd("BufWritePost", {
--   pattern = "*.xml",
--   callback = function()
--     vim.cmd("FormatXml")
--   end,
-- })
--
-- -- Maven compile command to load new plugins in pom.xml
-- vim.api.nvim_create_user_command("MvnCompile", function()
--   -- open a new terminal window and run mvn clean compile
--   vim.cmd("botright split | terminal mvn clean compile")
-- end, { desc = "Run 'mvn clean compile' in a terminal" })
--
-- vim.api.nvim_create_user_command("NewJavaInPackage", function()
--   local scan = require("plenary.scandir")
--   local Path = require("plenary.path")
--
--   local root = "src/main/java"
--   local dirs = scan.scan_dir(root, { only_dirs = true, depth = 10 })
--
--   local packages = {}
--   for _, dir in ipairs(dirs) do
--     local rel = Path:new(dir):make_relative(root)
--     if rel ~= "." then
--       packages[#packages + 1] = rel:gsub("/", ".")
--     end
--   end
--
--   require("fzf-lua").fzf_exec(packages, {
--     prompt = "Select package> ",
--     actions = {
--       ["default"] = function(selected)
--         local pkg = selected[1]
--         vim.ui.input({ prompt = "Class name: " }, function(classname)
--           if not classname or classname == "" then
--             return
--           end
--           local path = root .. "/" .. pkg:gsub("%.", "/") .. "/" .. classname .. ".java"
--           vim.fn.mkdir(vim.fn.fnamemodify(path, ":h"), "p")
--           vim.cmd("edit " .. path)
--           vim.fn.append(0, {
--             "package " .. pkg .. ";",
--             "",
--             "public class " .. classname .. " {",
--             "    ",
--             "}",
--           })
--           vim.cmd("normal! 4G4|")
--         end)
--       end,
--     },
--   })
-- end, { desc = "Create a Java class inside a selected package" })
--
-- local function get_listed_buffers()
--   return vim.fn.getbufinfo({ buflisted = 1 })
-- end
--
-- vim.api.nvim_create_user_command("BDeleteRight", function()
--   local current_buf = vim.api.nvim_get_current_buf()
--   local bufs = get_listed_buffers()
--
--   local current_index
--   for i, buf in ipairs(bufs) do
--     if buf.bufnr == current_buf then
--       current_index = i
--       break
--     end
--   end
--   if not current_index then
--     print("Current buffer not found.")
--     return
--   end
--
--   for i = current_index + 1, #bufs do
--     vim.api.nvim_buf_delete(bufs[i].bufnr, { force = true })
--   end
--   print("Closed all buffers to the right.")
-- end, { desc = "Close all buffers to the right of current buffer" })
--
-- vim.api.nvim_create_user_command("BDeleteLeft", function()
--   local current_buf = vim.api.nvim_get_current_buf()
--   local bufs = get_listed_buffers()
--
--   local current_index
--   for i, buf in ipairs(bufs) do
--     if buf.bufnr == current_buf then
--       current_index = i
--       break
--     end
--   end
--   if not current_index then
--     print("Current buffer not found.")
--     return
--   end
--
--   for i = 1, current_index - 1 do
--     vim.api.nvim_buf_delete(bufs[i].bufnr, { force = true })
--   end
--   print("Closed all buffers to the left.")
-- end, { desc = "Close all buffers to the left of current buffer" })
--
-- vim.api.nvim_create_user_command("BDeleteOther", function()
--   local current_buf = vim.api.nvim_get_current_buf()
--   local bufs = get_listed_buffers()
--
--   for _, buf in ipairs(bufs) do
--     if buf.bufnr ~= current_buf then
--       vim.api.nvim_buf_delete(buf.bufnr, { force = true })
--     end
--   end
--   print("Closed all other buffers.")
-- end, { desc = "Close all buffers except current buffer" })
--
-- vim.keymap.set("n", "<leader>jr", function()
--   -- Save current file
--   vim.cmd("write")
--
--   local project_root = vim.fn.getcwd()
--   local absolute_path = vim.fn.expand("%:p")
--   local rel_path = absolute_path:sub(#project_root + 2) -- +2 to remove the "/" too
--
--   local prefix = "src/main/java/"
--   if rel_path:sub(1, #prefix) ~= prefix then
--     vim.notify("File is not under src/main/java", vim.log.levels.ERROR)
--     return
--   end
--
--   local class_path = rel_path:sub(#prefix + 1):gsub("%.java$", "")
--   local main_class = class_path:gsub("/", ".")
--
--   vim.cmd("split | terminal mvn compile && java -cp target/classes " .. main_class)
--   vim.cmd("startinsert")
-- end, { desc = "Compile and run current Java file via Maven" })
--
-- -- Theme Chooser : to change theme rapidly
-- vim.keymap.set("n", "<leader>tc", function()
--   local themes = vim.fn.getcompletion("", "color")
--   vim.ui.select(themes, { prompt = "Select colorscheme:" }, function(choice)
--     if choice then
--       -- Apply theme
--       vim.cmd.colorscheme(choice)
--
--       -- Save choice to ~/.config/nvim/theme.lua
--       local path = vim.fn.stdpath("config") .. "/theme.lua"
--       local file = io.open(path, "w")
--       if file then
--         file:write("return " .. string.format("%q", choice) .. "\n")
--         file:close()
--         print("Saved theme:", choice)
--       else
--         print("Error: Could not write theme file.")
--       end
--     end
--   end)
-- end, { desc = "Pick and save colorscheme" })
--
-- -- Load theme on startup from ~/.config/nvim/theme.lua
-- local ok, theme = pcall(dofile, vim.fn.stdpath("config") .. "/theme.lua")
-- if ok and theme then
--   vim.cmd.colorscheme(theme)
-- end
